### PR TITLE
Update tox.ini

### PR DESCRIPTION
**Pull request by jnsgruk**
Remove `whitelist_externals` to tidy up our language, the setting is also deprecated in favour of `allowlist_externals`

https://tox.readthedocs.io/en/latest/config.html#conf-allowlist_externals

### CODE REVIEW

**Review by balbirthomas — APPROVED** [review]

**Review by dstathis — CHANGES_REQUESTED** [review]
The version of tox in 20.04 LTS does not recognize allowlist.

**Comment by dstathis** [comment]
By the way, is there a way to just say "I don't approve" without requesting changes?

**Comment by jnsgruk** [comment]
Surely tox is installed independently through `pip`?

**Comment by dstathis** [comment]
> Surely tox is installed independently through `pip`?

It certainly could be. I installed it using apt. There is more or less no reason to develop in a virtualenv for charms, especially when using tox so I have things installed using the system package manager.

As a note, charmcraft itself throws an error if you try to use the pip installed version.

**Review by dstathis — APPROVED** [review]

**Comment by dstathis** [comment]
After some discussion I have decided to merge this. The issue on system installed tox is only a warning.

**Pull request merged**
